# Site settings
title: Iron Mountain Roller Girls
email: webinfo@ironmountainrollergirls.com
description: > # this means to ignore newlines until "baseurl:"
    Iron Mountain Roller Girls, Cumberland's one and only Roller Derby Team!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ironmountainrollergirls.com" # the base hostname & protocol for your site
twitter_username: imrg_derby
github_username:  kimmellj

# Build settings
markdown: kramdown
cdn_url: http://d3hm7pdbttd4nl.cloudfront.net/imrg-dist/dist/
use_cdn: remote
